author: alrik94
database: false
description: Logs chat and commands
main: me.alrik94.plugins.cclogger.CCLogger
name: CCLogger
startup: postworld
version: '3.1.2'
permissions:
  cclogger.notify:
    description: Players with this permission get notified when a player says anything on the chat or command notify list.
    default: op
  cclogger.exempt:
    description: Players with this permission do not get logged for anything.
    default: op
commands:
  ccreload:
    description: This command reloads the CCLogger configuration.
    usage: /<command>
    permission: cclogger.reload
    permission-message: You don't have permission to use this command!